### ISSUE TITLE
Read about monetization in app stores

### ISSUE THREAD

**Issue by BokerBob** [tesss/find-me#3]

**Comment by carpeviem** [comment]
Googleplay:
https://support.google.com/googleplay/android-developer/answer/2700656?hl=ru
https://support.google.com/googleplay/android-developer?source=404#topic=3450769

**Comment by carpeviem** [comment]
APP:
https://www.apple-iphone.ru/review/kak-zaregistrirovat-akkaunt-razrab/
https://habrahabr.ru/post/171787/
https://habrahabr.ru/company/payoneer/blog/166119/
