### ISSUE TITLE
Read about OSM license

### ISSUE THREAD

**Issue by BokerBob** [tesss/find-me#4]

**Comment by carpeviem** [comment]
Если используются изображения с наших серверов (тайлы OpenStreetMap), т.е. Mapnik или Osmarender/tiles@home, необходимо написать, как минимум, «© участники проекта OpenStreetMap, CC-BY-SA».
Если используются только данные OpenStreetMap, необходимо написать «Данные карты © участники проекта OpenStreetMap, ODbL».
Там, где это возможно, слово «OpenStreetMap» должно являться ссылкой на http://www.openstreetmap.org/, а «ODbL» — на http://opendatacommons.org/licenses/odbl/. Если используется носитель, где ссылки разместить невозможно (например, что-то напечатанное), мы советуем направлять ваших читателей на www.openstreetmap.org (возможно, разворачивая 'OpenStreetMap' до своего полного адреса) и на www.opendatacommons.org.

Хорошие примеры такого подхода: [1], [2], [3].

Где разместить

Упоминание необходимо разместить в месте, «соответствующем используемому носителю или подходам». Другими словами, упоминайте OpenStreetMap так же и в том же месте, как любого другого поставщика карт.

Обычная интерпретация этого правила такова:

Для просматриваемой электронной карты (то есть, встроенной в вебстраницу или приложение для мобильного телефона), упоминания обычно делаются в углу карты, как это делают другие сервисы, например, Google Maps.
Джерело:http://wiki.openstreetmap.org/wiki/RU:%D0%9F%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D0%B5_%D0%92%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B_%D0%B8_%D0%9E%D1%82%D0%B2%D0%B5%D1%82%D1%8B#.D0.AF_.D1.85.D0.BE.D1.87.D1.83_.D0.B8.D1.81.D0.BF.D0.BE.D0.BB.D1.8C.D0.B7.D0.BE.D0.B2.D0.B0.D1.82.D1.8C_.D0.BA.D0.B0.D1.80.D1.82.D1.8B_OpenStreetMap._.D0.A7.D1.82.D0.BE_.D0.BC.D0.BD.D0.B5_.D0.BD.D0.B0.D0.B4.D0.BE_.D0.BD.D0.B0.D0.BF.D0.B8.D1.81.D0.B0.D1.82.D1.8C.3F
